INFR-75 | Use testplan instead of testScript

diff --git a/.github/workflows/fyrstain.yml b/.github/workflows/fyrstain.yml
--- a/.github/workflows/fyrstain.yml
+++ b/.github/workflows/fyrstain.yml
@@ -112,7 +112,7 @@ jobs:
       - name: Trigger test
         id: trigger
         run: |
-          RESPONSE=$(curl -s -X POST "$TESTBED_URL/TestScript/TS-careCircle-create/\$launchTest" \
+          RESPONSE=$(curl -s -X POST "$TESTBED_URL/TestPlan/TP-SOC-07/\$launchTest" \
             -H "Content-Type: application/fhir+json" \
             -d '{"resourceType":"Parameters","parameter":[{"name":"serverID","valueString":"ci-mapping-engine"},{"name":"clientID","valueString":"db5bd2c0-2342-4567-9740-dd6ada4b9eb3"},{"name":"automatic","valueBoolean":true}]}')
           echo "Full response: $RESPONSE"
@@ -121,10 +121,13 @@ jobs:
       - name: Poll test result
         run: |
           for i in {1..20}; do
-            RESULT=$(curl -s "$TESTBED_URL/TestReport/${{ steps.trigger.outputs.id }}" | jq -r .result)
+            RESULT=$(curl -s "$TESTBED_URL/TestPlan/${{ steps.trigger.outputs.id }}" | jq -r '.assertion[].type.coding[] | select(.system=="https://fyrstain.com/testPlanResult") | .code')
             echo "Result: $RESULT"
-            if [ "$RESULT" = "pass" ]; then exit 0; fi
-            if [ "$RESULT" = "fail" ]; then exit 1; fi
+            if [[ "$RESULT" == "pass" || "$RESULT" == "warning" || "$RESULT" == "skip" ]]; then
+              exit 0
+            elif [[ "$RESULT" == "fail" || "$RESULT" == "error" ]]; then
+              exit 1
+            fi
             sleep 10
           done
           echo "Timeout waiting for test"
@@ -140,6 +143,8 @@ jobs:
         run: |
           curl -s -X DELETE "$TESTBED_URL/Device/ci-mapping-engine"
           curl -s -X DELETE "$TESTBED_URL/Endpoint/ci-mapping-engine-endpoint"
+
+#TODO REMOVE DOCKER IMAGE
 
       - name: Stop and clean container
         run: |
